name: Release

on:
  push:
    tags:
      - v**

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: GoReleaser Action
      uses: goreleaser/goreleaser-action@v1.1.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
